
services:
  # ---------- Database ----------
  postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports: ["5432:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: airflow_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: ["5050:80"]
    depends_on: [postgres]

  # ---------- Airflow ----------
  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airflow_webserver
    depends_on: [postgres]
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./spark-app:/opt/airflow/spark-app
      - ./logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    ports: ["8080:8080"]
    entrypoint: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin &&
        exec airflow webserver"

  # ---------- Spark ----------
  spark-master:
    build:
      context: .
      dockerfile: spark-custom.Dockerfile
    container_name: spark-master
    environment: [SPARK_MODE=master]
    ports:
      - "7077:7077"
      - "8088:8080"
    volumes:
      - ./spark-app:/opt/spark-app
      - ./logs:/logs

  spark-worker:
    build:
      context: .
      dockerfile: spark-custom.Dockerfile
    container_name: spark-worker
    depends_on: [spark-master]
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    ports: ["8089:8081"]
    volumes:
      - ./spark-app:/opt/spark-app
      - ./logs:/logs

  # ---------- Portainer (opsiyonel) ----------
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports: ["9000:9000"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  postgres_data:
  portainer_data:
